--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset GRANTS_TO_USERS:1 runOnChange:true stripComments:true
--labels: "GRANTS_TO_USERS or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_GRANTS_TO_USERS AS
SELECT *
  FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS;

-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_GRANTS_TO_USERS;