--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset UDF_METERING_HISTORY:1 runOnChange:true stripComments:true
--labels: UDF_METERING_HISTORY
create or replace function CDOPS_STATESTORE.REPORTING.UDF_METERING_HISTORY(PATTERN VARCHAR,TYPE ARRAY, STARTDATE DATE, ENDDATE DATE)
returns table (
  START_TIME TIMESTAMP_LTZ,
  END_TIME TIMESTAMP_LTZ,
  ENTITY_ID NUMBER,
  NAME VARCHAR,
  SERVICE_TYPE VARCHAR,
  CREDITS_USED NUMBER(38,9),
  CREDITS_USED_COMPUTE NUMBER(38,9),
  CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
  START_DATE DATE,
  OPERATION_HOURS NUMBER,
  TIME_OF_DAY TIME
) as
'
    SELECT START_TIME::TIMESTAMP_LTZ(9),
        END_TIME::TIMESTAMP_LTZ(9),
        ENTITY_ID,
        NAME,
        SERVICE_TYPE,
        CREDITS_USED,
        CREDITS_USED_COMPUTE,
        CREDITS_USED_CLOUD_SERVICES,
        TO_DATE(START_TIME) AS START_DATE,
        DATEDIFF(HOUR, START_TIME, END_TIME) AS OPERATION_HOURS,
        TO_TIME(START_TIME) AS TIME_OF_DAY
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY WHERE
    RLIKE (NAME,PATTERN) AND
    TO_DATE(START_TIME) >= STARTDATE AND TO_DATE(END_TIME) <= ENDDATE
    AND ARRAY_CONTAINS(SERVICE_TYPE::VARIANT,TYPE)
    ORDER BY START_TIME
';
-- rollback DROP FUNCTION IF EXISTS CDOPS_STATESTORE.REPORTING.UDF_METERING_HISTORY(VARCHAR, ARRAY,  DATE,  DATE);

