--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_ACCOUNT_MEMBERSHIP:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_ACCOUNT_MEMBERSHIP or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ACCOUNT_MEMBERSHIP as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.ACCOUNT_MEMBERSHIP;

-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ACCOUNT_MEMBERSHIP;