--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_DESTINATION:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_DESTINATION or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_DESTINATION as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.DESTINATION;


-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_DESTINATION;