--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_AUDIT:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_AUDIT or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_AUDIT as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.FIVETRAN_AUDIT;


-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_AUDIT;