--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_INCREMENTAL_MAR:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_INCREMENTAL_MAR or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_INCREMENTAL_MAR as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.INCREMENTAL_MAR;

-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_INCREMENTAL_MAR;