--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_RESOURCE_MEMBERSHIP:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_RESOURCE_MEMBERSHIP or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_RESOURCE_MEMBERSHIP as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.RESOURCE_MEMBERSHIP;



-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_RESOURCE_MEMBERSHIP;