--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_ROLE:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_ROLE or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ROLE as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.ROLE;


-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ROLE;