--liquibase formatted sql
--preconditions onFail:HALT onError:HALT

--changeset FIVETRAN_ROLE_PERMISSION:1 runOnChange:true stripComments:true
--labels: "FIVETRAN_ROLE_PERMISSION or GENERIC"

CREATE OR REPLACE VIEW   CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ROLE_PERMISSION as
SELECT *
  FROM FIVETRAN_TERRAFORM_LAB_DB.FIVETRAN_LOG.ROLE_PERMISSION;


-- rollback DROP VIEW IF EXISTS CDOPS_STATESTORE.REPORTING_EXT.VW_FIVETRAN_ROLE_PERMISSION;